<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkpController;
use App\Http\Controllers\AnakController;
use App\Http\Controllers\CutiController;
use App\Http\Controllers\ArsipController;
use App\Http\Controllers\DinasController;
use App\Http\Controllers\IstriController;
use App\Http\Controllers\KuasaController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SuratController;
use App\Http\Controllers\EdaranController;
use App\Http\Controllers\NotulaController;
use App\Http\Controllers\HukumanController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DisposisiController;
use App\Http\Controllers\EpersonalController;
use App\Http\Controllers\NominatifController;
use App\Http\Controllers\NotaDinasController;
use App\Http\Controllers\PanggilanController;
use App\Http\Controllers\PembinaanController;
use App\Http\Controllers\PenetapanController;
use App\Http\Controllers\PengantarController;
use App\Http\Controllers\StatistikController;
use App\Http\Controllers\KeteranganController;
use App\Http\Controllers\OrganisasiController;
use App\Http\Controllers\PendidikanController;
use App\Http\Controllers\BeritaAcaraController;
use App\Http\Controllers\IjinBelajarController;
use App\Http\Controllers\PenghargaanController;
use App\Http\Controllers\DiklatteknikController;
use App\Http\Controllers\PegawaiPrintController;
use App\Http\Controllers\TugasBelajarController;
use App\Http\Controllers\DiklatJabatanController;
use App\Http\Controllers\PemberianIzinController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\KeteranganRawatController;
use App\Http\Controllers\DiklatFungsionalController;
use App\Http\Controllers\PengumumanController;
use App\Http\Controllers\PerintahController;
use App\Http\Controllers\PerjalananDinasController;
use App\Http\Controllers\PernyataanController;
use App\Http\Controllers\SertifikatController;
use App\Http\Controllers\TelaahanController;
use App\Http\Controllers\TugasController;

Route::middleware('guest')->group(function () {
    Route::redirect('/', '/login');
    Route::get('/login', [LoginController::class, 'index'])->name('login');
});

Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');


Route::middleware('auth')->group(function () {
    Route::get('/dashboard/change-password', [ResetPasswordController::class, 'showChangePasswordForm'])->name('password.change');
    Route::post('/dashboard/change-password', [ResetPasswordController::class, 'updatePassword'])->name('password.update');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/search', [DashboardController::class, 'search'])->name('search');
    Route::get('/dashoard/epersonal', [EpersonalController::class, 'index'])->name('dashboard.epersonal');
    Route::get('/search', [EpersonalController::class, 'search'])->name('search');
    Route::resource('/dashboard/pegawai', PegawaiController::class);
    Route::put('/dashboard/pegawai/{id}/update-image', [PegawaiController::class, 'updateImage'])->name('pegawai.update-image');
    Route::get('/pegawai/search', [PegawaiController::class, 'search'])->name('pegawai.search');
    Route::get('/arsip/view/{id}', [ArsipController::class, 'arsipView'])->name('arsip.view');
    Route::get('/rekap-kgb-pangkat', [App\Http\Controllers\PegawaiController::class, 'rekapKGBPangkat'])->name('rekap.kgbpangkat');
    Route::resource('/dashboard/istri', IstriController::class);
    Route::resource('/dashboard/anak', AnakController::class);
    Route::resource('/dashboard/diklatfungsional', DiklatFungsionalController::class);
    Route::resource('/dashboard/diklatjabatan', DiklatJabatanController::class);
    Route::resource('/dashboard/diklatteknik', DiklatteknikController::class);
    Route::resource('/dashboard/jabatan', JabatanController::class);
    Route::resource('/dashboard/penghargaan', PenghargaanController::class);
    Route::resource('/dashboard/organisasi', OrganisasiController::class);
    Route::resource('/dashboard/pendidikan', PendidikanController::class);
    Route::resource('/dashboard/ijinbelajar', IjinBelajarController::class);
    Route::resource('/dashboard/arsip', ArsipController::class);

    Route::post('/pegawai/{id}/print/preview', [PegawaiPrintController::class, 'preview'])->name('pegawai.print.preview');
    Route::post('/pegawai/{id}/print/cetak', [PegawaiPrintController::class, 'cetak'])->name('pegawai.print.cetak');

    Route::get('/dashboard/statistik', [StatistikController::class, 'index'])->name('statistik.index');
    Route::get('/statistik/preview', [StatistikController::class, 'preview'])->name('statistik.preview');
    Route::get('/dashboard/statistik/cetak_pdf', [StatistikController::class, 'cetak'])->name('statistik.cetak');
    Route::prefix('/dashboard/nominatif')->name('dashboard.nominatif.')->group(function () {
        Route::get('/', [NominatifController::class, 'index'])->name('index');
        Route::post('/', [NominatifController::class, 'index']);
        Route::get('/clear', [NominatifController::class, 'clearResults'])->name('clear');
        Route::get('/cetak', [NominatifController::class, 'cetak'])->name('cetak');
        Route::get('/preview', [NominatifController::class, 'preview'])->name('preview');
        Route::get('/export-excel', [NominatifController::class, 'exportExcel'])->name('exportExcel');
    });
    Route::get('/dashboard/rekap-golongan', [PegawaiController::class, 'rekapGolongan'])->name('rekap.golongan');
    Route::get('/dashboard/rekap-jabatan', [JabatanController::class, 'rekapJabatan'])->name('rekap.jabatan');
    Route::get('/dashboard/rekap-eselon', [JabatanController::class, 'rekapEselon'])->name('rekap.eselon');
    Route::get('/dashboard/rekap-kepegawaian', [JabatanController::class, 'rekapKepegawaian'])->name('rekap.kepegawaian');
    Route::get('/dashboard/rekap-agama', [PegawaiController::class, 'rekapAgama'])->name('rekap.agama');
    Route::get('/dashboard/rekap-jenis-kelamin', [PegawaiController::class, 'rekapJenisKelamin'])->name('rekap.jeniskelamin');
    Route::get('/dashboard/rekap-status-nikah', [PegawaiController::class, 'rekapStatusNikah'])->name('rekap.statusnikah');
    Route::get('/dashboard/rekap-pendidikan-akhir', [PendidikanController::class, 'rekapPendidikanAkhir'])->name('rekap.pendidikanakhir');

    Route::get('/surat', [SuratController::class, 'index'])->name('surat');
    Route::get('/api/pegawai/{id}', [PegawaiController::class, 'getData']);
    Route::resource('cuti', CutiController::class);
    Route::get('/cuti/{id}/export', [CutiController::class, 'export'])->name('cuti.export');
    Route::resource('rawat', KeteranganRawatController::class);
    Route::get('/rawat/{id}/export', [KeteranganRawatController::class, 'export'])->name('rawat.export');
    Route::resource('tugas_belajar', TugasBelajarController::class);
    Route::get('/tugas_belajar/{id}/export', [TugasBelajarController::class, 'export'])->name('tugas_belajar.export');
    Route::resource('hukuman', HukumanController::class);
    Route::get('/hukuman/{id}/export', [HukumanController::class, 'export'])->name('hukuman.export');
    Route::resource('pembinaan', PembinaanController::class);
    Route::get('/pembinaan/{id}/export', [PembinaanController::class, 'export'])->name('pembinaan.export');
    Route::resource('berita_acara', BeritaAcaraController::class);
    Route::get('/berita_acara/{id}/export', [BeritaAcaraController::class, 'export'])->name('berita_acara.export');
    Route::resource('dinas', DinasController::class);
    Route::get('/dinas/{id}/export', [DinasController::class, 'export'])->name('dinas.export');
    Route::resource('disposisi', DisposisiController::class);
    Route::get('/disposisi/{id}/export', [DisposisiController::class, 'export'])->name('disposisi.export');
    Route::resource('edaran', EdaranController::class);
    Route::get('/edaran/{id}/export', [EdaranController::class, 'export'])->name('edaran.export');
    Route::resource('keterangan', KeteranganController::class);
    Route::get('/keterangan/{id}/export', [KeteranganController::class, 'export'])->name('keterangan.export');
    Route::resource('kuasa', KuasaController::class);
    Route::get('kuasa/{id}/export', [KuasaController::class, 'export'])->name('kuasa.export');
    Route::resource('nota_dinas', NotaDinasController::class);
    Route::get('nota_dinas/{id}/export', [NotaDinasController::class, 'export'])->name('nota_dinas.export');
    Route::resource('notula', NotulaController::class);
    Route::get('notula/{id}/export', [NotulaController::class, 'export'])->name('notula.export');
    Route::resource('panggilan', PanggilanController::class);
    Route::get('panggilan/{id}/export', [PanggilanController::class, 'export'])->name('panggilan.export');
    Route::resource('pemberian_izin', PemberianIzinController::class);
    Route::get('pemberian_izin/{id}/export', [PemberianIzinController::class, 'export'])->name('pemberian_izin.export');
    Route::resource('penetapan', PenetapanController::class);
    Route::get('penetapan/{id}/export', [PenetapanController::class, 'export'])->name('penetapan.export');
    Route::resource('pengantar', PengantarController::class);
    Route::get('pengantar/{id}/export', [PengantarController::class, 'export'])->name('pengantar.export');
    Route::resource('pengumuman', PengumumanController::class);
    Route::get('pengumuman/{id}/export', [PengumumanController::class, 'export'])->name('pengumuman.export');
    Route::resource('perintah', PerintahController::class);
    Route::get('perintah/{id}/export', [PerintahController::class, 'export'])->name('perintah.export');
    Route::resource('perjalanan_dinas', PerjalananDinasController::class);
    Route::get('perjalanan_dinas/{id}/export', [PerjalananDinasController::class, 'export'])->name('perjalanan_dinas.export');
    Route::resource('pernyataan', PernyataanController::class);
    Route::get('pernyataan/{id}/export', [PernyataanController::class, 'export'])->name('pernyataan.export');
    Route::resource('sertifikat', SertifikatController::class);
    Route::get('sertifikat/{id}/export', [SertifikatController::class, 'export'])->name('sertifikat.export');
    Route::resource('telaahan', TelaahanController::class);
    Route::get('telaahan/{id}/export', [TelaahanController::class, 'export'])->name('telaahan.export');
    Route::resource('tugas', TugasController::class);
    Route::get('tugas/{id}/export', [TugasController::class, 'export'])->name('tugas.export');

    
    Route::resource('skp', SkpController::class);
    Route::get('/skp/{skp}/cetak/pdf', [SkpController::class, 'cetakPdf'])->name('skp.cetak.pdf');
    Route::get('/skp/{skp}/cetak/word', [SkpController::class, 'cetakWord'])->name('skp.cetak.word');
    Route::get('/skp/{skp}/cetak/excel', [SkpController::class, 'cetakExcel'])->name('skp.cetak.excel');
});
